apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "streamingapp.name" . }}-config
  labels:
    {{- include "streamingapp.labels" . | nindent 4 }}
data:
  MONGO_URI: mongodb://{{ include "streamingapp.name" . }}-mongo:27017/{{ .Values.mongo.database }}
  CLIENT_URLS: {{ .Values.config.clientUrls | quote }}
  AWS_REGION: {{ .Values.global.awsRegion | quote }}
  AWS_S3_BUCKET: {{ .Values.config.awsS3Bucket | quote }}
  AWS_CDN_URL: {{ .Values.config.awsCdnUrl | quote }}
  STREAMING_PUBLIC_URL: {{ .Values.config.streamingPublicUrl | quote }}
