{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "streamingapp.name" . }}
  labels:
    {{- include "streamingapp.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /api/auth
            pathType: Prefix
            backend: { service: { name: streamingapp-auth, port: { number: 3001 } } }
          - path: /api/streaming
            pathType: Prefix
            backend: { service: { name: streamingapp-streaming, port: { number: 3002 } } }
          - path: /api/admin
            pathType: Prefix
            backend: { service: { name: streamingapp-admin, port: { number: 3003 } } }
          - path: /api/chat
            pathType: Prefix
            backend: { service: { name: streamingapp-chat, port: { number: 3004 } } }
          - path: /socket.io
            pathType: Prefix
            backend: { service: { name: streamingapp-chat, port: { number: 3004 } } }
          - path: /
            pathType: Prefix
            backend: { service: { name: streamingapp-frontend, port: { number: 80 } } }
{{- end }}
