apiVersion: v1
kind: Service
metadata:
  name: {{ include "streamingapp.name" . }}-mongo
  labels:
    {{- include "streamingapp.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongo
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ include "streamingapp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: mongo
  ports:
    - name: mongo
      port: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "streamingapp.name" . }}-mongo
  labels:
    {{- include "streamingapp.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongo
spec:
  serviceName: {{ include "streamingapp.name" . }}-mongo
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "streamingapp.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: mongo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "streamingapp.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: mongo
    spec:
      containers:
        - name: mongo
          image: {{ .Values.mongo.image | quote }}
          ports:
            - name: mongo
              containerPort: 27017
          readinessProbe:
            tcpSocket: { port: mongo }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket: { port: mongo }
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            {{- toYaml .Values.mongo.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.mongo.storageClassName | quote }}
        resources:
          requests:
            storage: {{ .Values.mongo.storageSize }}
