{{- range $name, $service := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "streamingapp.name" $ }}-{{ $name }}
  labels:
    {{- include "streamingapp.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "streamingapp.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: {{ $name }}
  ports:
    - name: http
      port: {{ $service.port }}
      targetPort: http
{{- end }}
