apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandboxev-reports-ng
  namespace: default
  labels:
   app: sandboxev-reports-ng
spec:
  selector:
    matchLabels:
      run: sandboxev-reports-ng
  replicas: 1
  template:
    metadata:
      labels:
        run: sandboxev-reports-ng
        app: sandboxev-reports-ng
      annotations:
#        prometheus.io/scrape: 'true'
#        prometheus.io/port: '80'
    spec:
      containers:
      - image: sandboxmreg2.clubwise.com/ng/reports:1.2.0-22007-1
        imagePullPolicy: Always
        name: sandboxev-reports-ng
        env:
        - name: PORT
          value: "80"
        - name: HOST
          value: "sandboxevreportsng.clubwise.com"

        volumeMounts:
        - mountPath: /usr/share/nginx/html/assets/config.json
          name: sandbox-reports-ng-volume
          subPath: config.json
      volumes:
      - name: sandbox-reports-ng-volume
        hostPath:
          path: /authsvc/cert/sandboxevreportsng
          type: Directory

      imagePullSecrets:
      - name : sandboxmreg2
---

 apiVersion: v1
 kind: Service
 metadata:
  name: sandboxev-reports-ng
  namespace: default
 spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: sandboxev-reports-ng

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sandboxev-reports-ng
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: sandboxevreportsng.clubwise.com
    http:
      paths:
        - pathType: Prefix
          path: /
          backend:
            service:
              name: sandboxev-reports-ng
              port:
                number: 80